# Generated by Django 5.2.12 on 2026-04-03 02:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facility_admin', '0001_initial'),
        ('member_access', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('InstructorID', models.AutoField(primary_key=True, serialize=False)),
                ('FirstName', models.CharField(max_length=100)),
                ('LastName', models.CharField(max_length=100)),
                ('Specialization', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('HireDate', models.DateField()),
                ('Phone', models.CharField(max_length=20)),
                ('Status', models.CharField(default='Active', max_length=20)),
                ('AvailabilityNote', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('ClassID', models.AutoField(primary_key=True, serialize=False)),
                ('ClassName', models.CharField(max_length=100)),
                ('ClassType', models.CharField(max_length=50)),
                ('MaxCapacity', models.IntegerField()),
                ('DifficultyLevel', models.CharField(max_length=50)),
                ('DurationMinutes', models.IntegerField()),
                ('RoomID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='facility_admin.room')),
            ],
        ),
        migrations.CreateModel(
            name='ClassSchedule',
            fields=[
                ('ScheduleID', models.AutoField(primary_key=True, serialize=False)),
                ('DayOfWeek', models.CharField(max_length=20)),
                ('StartTime', models.TimeField()),
                ('EndTime', models.TimeField()),
                ('ClassID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='class_ops.class')),
                ('InstructorID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='class_ops.instructor')),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('EnrollmentID', models.AutoField(primary_key=True, serialize=False)),
                ('EnrollmentDate', models.DateField(auto_now_add=True)),
                ('AttendanceStatus', models.CharField(max_length=20)),
                ('MemberID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member_access.member')),
                ('ScheduleID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='class_ops.classschedule')),
            ],
        ),
        migrations.CreateModel(
            name='InstructorShift',
            fields=[
                ('ShiftID', models.AutoField(primary_key=True, serialize=False)),
                ('ShiftDate', models.DateField()),
                ('StartTime', models.TimeField()),
                ('EndTime', models.TimeField()),
                ('InstructorID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='class_ops.instructor')),
            ],
        ),
    ]
