# Generated by Django 5.2.12 on 2026-04-03 02:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('member_access', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('PaymentID', models.AutoField(primary_key=True, serialize=False)),
                ('Amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('PaymentDate', models.DateTimeField(auto_now_add=True)),
                ('PaymentMethod', models.CharField(max_length=50)),
                ('Status', models.CharField(max_length=20)),
                ('TransactionReference', models.CharField(blank=True, max_length=100, null=True)),
                ('MemberID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member_access.member')),
            ],
        ),
    ]
