# Generated by Django 5.2.12 on 2026-04-03 02:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('MembershipID', models.AutoField(primary_key=True, serialize=False)),
                ('Type', models.CharField(max_length=50)),
                ('MonthlyFee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('AccessLevel', models.CharField(max_length=50)),
                ('DurationMonths', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('MemberID', models.AutoField(primary_key=True, serialize=False)),
                ('FirstName', models.CharField(max_length=100)),
                ('LastName', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('Phone', models.CharField(max_length=20)),
                ('DateJoined', models.DateField(auto_now_add=True)),
                ('Gender', models.CharField(blank=True, max_length=20, null=True)),
                ('EmergencyContactName', models.CharField(max_length=150)),
                ('EmergencyContactPhone', models.CharField(max_length=20)),
                ('MembershipID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='member_access.membership')),
            ],
        ),
    ]
