# Generated by Django 5.2.12 on 2026-04-03 02:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('RoomID', models.AutoField(primary_key=True, serialize=False)),
                ('RoomName', models.CharField(max_length=100)),
                ('Type', models.CharField(max_length=50)),
                ('Floor', models.IntegerField()),
                ('Capacity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('EquipmentID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('Category', models.CharField(max_length=50)),
                ('PurchaseDate', models.DateField()),
                ('Condition', models.CharField(max_length=50)),
                ('LastServiced', models.DateField(blank=True, null=True)),
                ('RoomID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='facility_admin.room')),
            ],
        ),
    ]
